name: strpsearch_env_old
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - qt-main
  - pymol-open-source
  - python=3.8.18
  - pandas
  - numpy
  - requests
  - typer
  - rich
  - matplotlib
  - seaborn
  - scipy
  - foldseek
  - tmalign
  - typing_extensions
  - biopython
